#ifndef VillageWalletClientSDKReference_Swift_h
#define VillageWalletClientSDKReference_Swift_h

#import <OpenAPIClient/OAIApiClient.h>
#import <OpenAPIClient/OAIDefaultConfiguration.h>
// load models
#import <OpenAPIClient/OAIBasket.h>
#import <OpenAPIClient/OAIBasketItems.h>
#import <OpenAPIClient/OAICommonPaymentBase.h>
#import <OpenAPIClient/OAICommonPaymentSummary.h>
#import <OpenAPIClient/OAICommonPaymentSummaryAllOf.h>
#import <OpenAPIClient/OAICommonTransactionSummary.h>
#import <OpenAPIClient/OAICommonTransactionSummaryAllOf.h>
#import <OpenAPIClient/OAICreateMerchantPaymentSessionResponse.h>
#import <OpenAPIClient/OAICreateMerchantPaymentSessionResponseData.h>
#import <OpenAPIClient/OAICreateMerchantSchemaResults.h>
#import <OpenAPIClient/OAICreatePaymentQRCodeResults.h>
#import <OpenAPIClient/OAICreatePaymentRequestResults.h>
#import <OpenAPIClient/OAICreatePaymentRequestResultsData.h>
#import <OpenAPIClient/OAICreatePaymentSessionRequest.h>
#import <OpenAPIClient/OAICreditCard.h>
#import <OpenAPIClient/OAICreditCardStepUp.h>
#import <OpenAPIClient/OAICustomerInstrumentsData.h>
#import <OpenAPIClient/OAICustomerPaymentDetail.h>
#import <OpenAPIClient/OAICustomerPaymentDetailAllOf.h>
#import <OpenAPIClient/OAICustomerPaymentDetails.h>
#import <OpenAPIClient/OAICustomerPaymentSessionPaymentSessionIdData.h>
#import <OpenAPIClient/OAICustomerPaymentSessionResult.h>
#import <OpenAPIClient/OAICustomerPaymentsPaymentRequestIdData.h>
#import <OpenAPIClient/OAICustomerPaymentsPaymentRequestIdDataSecondaryInstruments.h>
#import <OpenAPIClient/OAICustomerPreferences.h>
#import <OpenAPIClient/OAICustomerPreferencesResult.h>
#import <OpenAPIClient/OAICustomerTransactionDetail.h>
#import <OpenAPIClient/OAICustomerTransactionDetailAllOf.h>
#import <OpenAPIClient/OAICustomerTransactionSummary.h>
#import <OpenAPIClient/OAICustomerTransactionSummaryAllOf.h>
#import <OpenAPIClient/OAICustomerTransactionSummaryAllOfInstruments.h>
#import <OpenAPIClient/OAIDynamicPayload.h>
#import <OpenAPIClient/OAIError.h>
#import <OpenAPIClient/OAIGetCustomerPaymentInstrumentsResults.h>
#import <OpenAPIClient/OAIGetCustomerPaymentInstrumentsResultsData.h>
#import <OpenAPIClient/OAIGetCustomerPaymentInstrumentsResultsDataEverydayPay.h>
#import <OpenAPIClient/OAIGetCustomerPaymentResult.h>
#import <OpenAPIClient/OAIGetCustomerTransactionDetailsResults.h>
#import <OpenAPIClient/OAIGetCustomerTransactionsResult.h>
#import <OpenAPIClient/OAIGetCustomerTransactionsResultData.h>
#import <OpenAPIClient/OAIGetMerchantPaymentDetailsResults.h>
#import <OpenAPIClient/OAIGetMerchantPaymentsResults.h>
#import <OpenAPIClient/OAIGetMerchantPaymentsResultsData.h>
#import <OpenAPIClient/OAIGetMerchantTransactionDetailsResults.h>
#import <OpenAPIClient/OAIGetMerchantTransactionsResults.h>
#import <OpenAPIClient/OAIGetMerchantTransactionsResultsData.h>
#import <OpenAPIClient/OAIGiftCard.h>
#import <OpenAPIClient/OAIGiftCardStepUp.h>
#import <OpenAPIClient/OAIHealthCheckResult.h>
#import <OpenAPIClient/OAIHealthCheckResultData.h>
#import <OpenAPIClient/OAIInitiatePaymentInstrumentAdditionResults.h>
#import <OpenAPIClient/OAIInitiatePaymentInstrumentAdditionResultsData.h>
#import <OpenAPIClient/OAIInstrumentAdditionDetails.h>
#import <OpenAPIClient/OAIMakeCustomerPaymentResults.h>
#import <OpenAPIClient/OAIMerchantPayload.h>
#import <OpenAPIClient/OAIMerchantPaymentDetail.h>
#import <OpenAPIClient/OAIMerchantPaymentDetailAllOf.h>
#import <OpenAPIClient/OAIMerchantPaymentRequest.h>
#import <OpenAPIClient/OAIMerchantPaymentSessionData.h>
#import <OpenAPIClient/OAIMerchantPaymentSummary.h>
#import <OpenAPIClient/OAIMerchantPaymentSummaryAllOf.h>
#import <OpenAPIClient/OAIMerchantPaymentsData.h>
#import <OpenAPIClient/OAIMerchantPreferences.h>
#import <OpenAPIClient/OAIMerchantQrData.h>
#import <OpenAPIClient/OAIMerchantSchema.h>
#import <OpenAPIClient/OAIMerchantSchemaData.h>
#import <OpenAPIClient/OAIMerchantSchemaDetailsResult.h>
#import <OpenAPIClient/OAIMerchantSchemaDetailsResultData.h>
#import <OpenAPIClient/OAIMerchantSchemaResult.h>
#import <OpenAPIClient/OAIMerchantSchemaResultData.h>
#import <OpenAPIClient/OAIMerchantSchemaSummary.h>
#import <OpenAPIClient/OAIMerchantTransactionDetail.h>
#import <OpenAPIClient/OAIMerchantTransactionSummary.h>
#import <OpenAPIClient/OAIMerchantTransactionSummaryAllOf.h>
#import <OpenAPIClient/OAIMerchantTransactionsTransactionIdRefundData.h>
#import <OpenAPIClient/OAIMetaPaginated.h>
#import <OpenAPIClient/OAIPaymentQRCodeDetails.h>
#import <OpenAPIClient/OAIPaymentSession.h>
#import <OpenAPIClient/OAIPosPayload.h>
#import <OpenAPIClient/OAIQr.h>
#import <OpenAPIClient/OAIRefundMerchantTransactionRequest.h>
#import <OpenAPIClient/OAIRefundMerchantTransactionResults.h>
#import <OpenAPIClient/OAIUpdatePaymentSessionRequest.h>
#import <OpenAPIClient/OAIUpdatePaymentSessionRequest1.h>
// load API classes for accessing endpoints
#import <OpenAPIClient/OAIAdministrationApi.h>
#import <OpenAPIClient/OAICustomerApi.h>
#import <OpenAPIClient/OAIMerchantApi.h>

#endif
